"""Streamlit interface for the Resume-Job Matcher.

Run locally with::

    streamlit run app/streamlit_app.py

Every number and sentence on this page comes from
:func:`src.pipeline.match_resume_to_job`. Nothing here is generated by a
language model, so the same two documents always produce the same report.
"""

from __future__ import annotations

import html
import sys
from pathlib import Path

import pandas as pd
import streamlit as st

# Make ``src`` importable when Streamlit runs this file directly.
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.config import (  # noqa: E402
    MAX_FILE_SIZE_MB,
    SAMPLE_JOBS_DIR,
    SAMPLE_RESUMES_DIR,
    MatchThresholds,
    ScoringWeights,
    Settings,
)
from src.parser import extract_text_safe  # noqa: E402
from src.pipeline import MatchReport, match_resume_to_job  # noqa: E402
from src.similarity import semantic_backend_available  # noqa: E402
from src.skill_extractor import SkillExtractor  # noqa: E402
from src.skill_normalizer import load_skill_vocabulary  # noqa: E402

st.set_page_config(
    page_title="Resume-Job Matcher",
    page_icon="◎",
    layout="wide",
    initial_sidebar_state="expanded",
)

SUPPORTED_TYPES = ["pdf", "docx", "txt", "md"]

# Colour roles. Each one carries meaning; none is decorative.
INK = "#14171F"
MUTED = "#5B6472"
LINE = "#E1E5EB"
ACCENT = "#2D4A7A"
MATCHED = "#1D7A5F"
MATCHED_BG = "#E7F3EE"
MISSING = "#B3402F"
MISSING_BG = "#FAEBE8"
PREFERRED = "#8A6017"
PREFERRED_BG = "#FBF1DF"
NEUTRAL_BG = "#EEF0F4"

BAND_COLOURS = ["#C6483A", "#C9861F", "#2F7D8C", "#1D7A5F"]


CSS = """
<style>
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600&display=swap');
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&display=swap');

html, body, [class*="css"], .stMarkdown, .stButton, .stRadio, .stSelectbox {
    font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif;
}
.block-container { padding-top: 2.4rem; max-width: 1180px; }

h1, h2, h3 { font-family: 'IBM Plex Sans', sans-serif; letter-spacing: -0.015em; }
h1 { font-weight: 600; font-size: 2rem; margin-bottom: .2rem; }
h2 { font-weight: 600; font-size: 1.15rem; margin-top: 2rem; }

.rjm-lede { color: #5B6472; font-size: .95rem; max-width: 62ch; line-height: 1.6; }

.rjm-step {
    font-family: 'IBM Plex Mono', monospace; font-size: .72rem; font-weight: 500;
    color: #2D4A7A; background: #EAEFF7; border-radius: 3px;
    padding: 2px 7px; margin-right: 8px;
}

.rjm-card {
    background: #FFFFFF; border: 1px solid #E1E5EB; border-radius: 10px;
    padding: 18px 20px;
}
.rjm-tile {
    background: #FFFFFF; border: 1px solid #E1E5EB; border-radius: 10px;
    padding: 14px 16px; height: 100%;
}
.rjm-tile-label { font-size: .74rem; color: #5B6472; letter-spacing: .02em; margin-bottom: 6px; }
.rjm-tile-value { font-family: 'IBM Plex Mono', monospace; font-size: 1.7rem; font-weight: 500;
                  color: #14171F; line-height: 1.1; font-variant-numeric: tabular-nums; }
.rjm-tile-note { font-size: .74rem; color: #5B6472; margin-top: 6px; line-height: 1.4; }

.rjm-score { font-family: 'IBM Plex Mono', monospace; font-size: 3.6rem; font-weight: 600;
             line-height: 1; font-variant-numeric: tabular-nums; }
.rjm-verdict { font-size: 1rem; font-weight: 500; margin-top: 6px; }

.rjm-chip {
    display: inline-block; font-size: .8rem; padding: 4px 10px; border-radius: 5px;
    margin: 0 5px 6px 0; line-height: 1.3;
}
.rjm-reason { font-size: .88rem; line-height: 1.55; margin-bottom: 7px; color: #14171F; }
.rjm-reason span.m { color: #1D7A5F; font-weight: 600; margin-right: 7px; }
.rjm-reason span.x { color: #B3402F; font-weight: 600; margin-right: 7px; }
.rjm-sub { font-size: .78rem; color: #5B6472; margin: 4px 0 12px; }

section[data-testid="stSidebar"] { background: #FFFFFF; border-right: 1px solid #E1E5EB; }
section[data-testid="stSidebar"] .block-container { padding-top: 1.5rem; }

div.stButton > button {
    background: #2D4A7A; color: #FFFFFF; border: none; border-radius: 7px;
    font-weight: 500; font-size: .95rem; padding: .6rem 1rem;
}
div.stButton > button:hover { background: #243C64; color: #FFFFFF; }

[data-testid="stFileUploaderDropzone"] { background: #FFFFFF; border: 1px dashed #C9D0DA; }
.stTabs [data-baseweb="tab"] { font-size: .9rem; }
</style>
"""


# --------------------------------------------------------------------------- #
# Cached resources
# --------------------------------------------------------------------------- #


@st.cache_resource(show_spinner=False)
def get_extractor() -> SkillExtractor:
    """Load the skill vocabulary once and share it across sessions."""
    return SkillExtractor(load_skill_vocabulary())


@st.cache_resource(show_spinner="Loading the semantic model (first run only)...")
def warm_semantic_model(model_name: str) -> str:
    """Load the sentence-transformer model once, before the first analysis."""
    from src.similarity import load_semantic_model

    return "sentence-transformers" if load_semantic_model(model_name) is not None else "lsa"


@st.cache_data(show_spinner=False)
def list_samples(directory: str) -> dict[str, str]:
    """Read the bundled sample documents."""
    samples: dict[str, str] = {}
    for path in sorted(Path(directory).glob("*.txt")):
        samples[path.stem.replace("_", " ").title()] = path.read_text(encoding="utf-8")
    return samples


@st.cache_data(show_spinner=False, max_entries=32)
def run_analysis(
    resume_text: str,
    job_text: str,
    weights: tuple[float, ...],
    thresholds: tuple[float, float, float],
    backend: str,
) -> MatchReport:
    """Run the pipeline. Cached so re-rendering does not recompute the match."""
    settings = Settings(
        weights=ScoringWeights(*weights),
        thresholds=MatchThresholds(*thresholds),
        semantic_backend=backend,
    )
    return match_resume_to_job(
        resume_text, job_text, settings=settings, extractor=get_extractor()
    )


# --------------------------------------------------------------------------- #
# Rendering helpers
# --------------------------------------------------------------------------- #


def esc(text: str) -> str:
    return html.escape(str(text))


def tile(label: str, value: str, note: str = "", colour: str = INK) -> str:
    """A metric tile.

    Written by hand rather than with ``st.metric`` because that widget renders
    every delta as a green up-arrow, which made shortfalls such as "Bachelor's
    is below the required Master's" read as good news.
    """
    note_html = f'<div class="rjm-tile-note">{esc(note)}</div>' if note else ""
    return (
        f'<div class="rjm-tile"><div class="rjm-tile-label">{esc(label)}</div>'
        f'<div class="rjm-tile-value" style="color:{colour}">{esc(value)}</div>'
        f"{note_html}</div>"
    )


def chips(items: list[str], fg: str, bg: str) -> str:
    if not items:
        return '<div class="rjm-sub">None</div>'
    return "".join(
        f'<span class="rjm-chip" style="color:{fg};background:{bg}">{esc(item)}</span>'
        for item in items
    )


def band_meter(score: float, thresholds: MatchThresholds, verdict: str) -> str:
    """Show where the score falls across all four configured bands.

    A plain progress bar says "69% full". This says "69.2 sits just past the
    Moderate/Strong boundary at 69" -- which is the interpretable-scoring claim
    the project makes, shown rather than asserted.
    """
    edges = [0.0, thresholds.weak_max, thresholds.moderate_max, thresholds.strong_max, 100.0]
    names = ["Weak", "Moderate", "Strong", "Excellent"]
    widths = [max(edges[i + 1] - edges[i], 0.1) for i in range(4)]
    position = min(max(score, 0.0), 100.0)

    segments = "".join(
        f'<div style="flex:{widths[i]};background:{BAND_COLOURS[i]};'
        f'opacity:{0.95 if names[i] in verdict else 0.22};height:100%"></div>'
        for i in range(4)
    )
    ticks = "".join(
        f'<span style="position:absolute;left:{edges[i + 1]}%;transform:translateX(-50%);'
        f'font-family:IBM Plex Mono,monospace;font-size:.66rem;color:{MUTED}">'
        f"{edges[i + 1]:.0f}</span>"
        for i in range(3)
    )
    labels = "".join(
        f'<div style="flex:{widths[i]};font-size:.7rem;color:{MUTED};text-align:center">'
        f"{names[i]}</div>"
        for i in range(4)
    )
    return (
        '<div style="margin-top:6px">'
        '<div style="position:relative;height:16px">'
        f'<div style="position:absolute;left:{position}%;transform:translateX(-50%);'
        f'font-size:.7rem;color:{INK};font-weight:600;white-space:nowrap">▼</div></div>'
        '<div style="display:flex;height:9px;border-radius:5px;overflow:hidden">'
        f"{segments}</div>"
        f'<div style="position:relative;height:14px;margin-top:3px">{ticks}</div>'
        f'<div style="display:flex">{labels}</div>'
        "</div>"
    )


def read_upload(uploaded) -> tuple[str, str | None]:
    if uploaded is None:
        return "", None
    return extract_text_safe(uploaded, filename=uploaded.name)


def document_input(label: str, key: str, samples_dir: Path, step: str) -> str:
    """Upload / paste / sample picker. Returns the document text."""
    st.markdown(
        f'<h2><span class="rjm-step">{step}</span>{esc(label)}</h2>', unsafe_allow_html=True
    )
    samples = list_samples(str(samples_dir))
    mode = st.radio(
        f"{label} source",
        ["Upload a file", "Paste text", "Use a sample"],
        key=f"{key}_mode",
        horizontal=True,
        label_visibility="collapsed",
    )

    if mode == "Upload a file":
        uploaded = st.file_uploader(
            f"PDF, DOCX or TXT, up to {MAX_FILE_SIZE_MB:.0f} MB",
            type=SUPPORTED_TYPES,
            key=f"{key}_file",
        )
        text, error = read_upload(uploaded)
        if error:
            st.error(error)
            return ""
        if text:
            st.markdown(
                f'<div class="rjm-sub">Read {len(text.split()):,} words from '
                f"{esc(uploaded.name)}</div>",
                unsafe_allow_html=True,
            )
            with st.expander("Preview extracted text"):
                st.text(text[:3000] + ("..." if len(text) > 3000 else ""))
        return text

    if mode == "Paste text":
        return st.text_area(
            f"Paste the {label.lower()}",
            height=240,
            key=f"{key}_paste",
            label_visibility="collapsed",
            placeholder=f"Paste the full {label.lower()} here...",
        )

    if not samples:
        st.warning(f"No sample files found in {samples_dir}")
        return ""
    choice = st.selectbox(
        f"Sample {label.lower()}", list(samples), key=f"{key}_sample",
        label_visibility="collapsed",
    )
    text = samples[choice]
    with st.expander("Preview sample"):
        st.text(text[:3000])
    return text


def render_verdict(report: MatchReport, thresholds: MatchThresholds) -> None:
    score = report.overall_score
    colour = MATCHED if score >= 70 else PREFERRED if score >= 40 else MISSING
    left, right = st.columns([1, 1.6], gap="large")

    with left:
        # One decimal place: the label is computed from the exact score, so
        # rounding 69.2 down to "69" made the verdict look inconsistent with
        # the Moderate band that ends at 69.
        st.markdown(
            f'<div class="rjm-card"><div class="rjm-score" style="color:{colour}">'
            f"{score:.1f}<span style='font-size:1.6rem'>%</span></div>"
            f'<div class="rjm-verdict" style="color:{colour}">{esc(report.classification)}</div>'
            + band_meter(score, thresholds, report.classification)
            + "</div>",
            unsafe_allow_html=True,
        )

    with right:
        rows = [
            f'<div class="rjm-reason"><span class="m">✓</span>{esc(reason)}</div>'
            for reason in report.result.explanations[:6]
        ] + [
            f'<div class="rjm-reason"><span class="x">✗</span>{esc(gap)}</div>'
            for gap in report.result.gaps[:6]
        ]
        st.markdown(
            '<div class="rjm-card"><div style="font-weight:600;font-size:.9rem;'
            'margin-bottom:10px">How this score was reached</div>'
            + "".join(rows)
            + "</div>",
            unsafe_allow_html=True,
        )


def render_dashboard(report: MatchReport) -> None:
    result = report.result
    required, preferred = result.required_gap, result.preferred_gap
    experience = result.component("experience")
    education = result.component("education")

    def pct(component) -> tuple[str, str, str]:
        if component is None or not component.available:
            return "n/a", "Not enough information; weight redistributed", MUTED
        value = component.value
        colour = MATCHED if value >= 0.75 else PREFERRED if value >= 0.4 else MISSING
        return f"{component.percent:.0f}%", component.detail, colour

    def tone(fraction: float) -> str:
        return MATCHED if fraction >= 0.75 else PREFERRED if fraction >= 0.4 else MISSING

    row = st.columns(4, gap="medium")
    row[0].markdown(
        tile("Required skill coverage", f"{required.coverage_percent:.0f}%",
             required.summary(), tone(required.coverage)),
        unsafe_allow_html=True,
    )
    if preferred.total:
        row[1].markdown(
            tile("Preferred skill coverage", f"{preferred.coverage_percent:.0f}%",
                 preferred.summary(), tone(preferred.coverage)),
            unsafe_allow_html=True,
        )
    else:
        row[1].markdown(
            tile("Preferred skill coverage", "n/a", "Not explicitly specified", MUTED),
            unsafe_allow_html=True,
        )
    row[2].markdown(
        tile("Semantic similarity", f"{report.semantic.score * 100:.0f}%",
             f"{report.semantic.backend} backend"),
        unsafe_allow_html=True,
    )
    row[3].markdown(
        tile("TF-IDF similarity", f"{report.tfidf_score * 100:.0f}%",
             f"Exact keyword overlap {report.keyword_score * 100:.0f}%"),
        unsafe_allow_html=True,
    )

    row2 = st.columns(4, gap="medium")
    value, note, colour = pct(experience)
    row2[0].markdown(tile("Experience match", value, note, colour), unsafe_allow_html=True)
    value, note, colour = pct(education)
    row2[1].markdown(tile("Education match", value, note, colour), unsafe_allow_html=True)
    row2[2].markdown(
        tile("Skills in resume", str(len(report.resume_skills.skills)),
             f"{len(report.additional_skills)} beyond this job"),
        unsafe_allow_html=True,
    )
    row2[3].markdown(
        tile("Skills in job", str(len(report.job.all_skills)),
             f"{required.total} required, {preferred.total} preferred"),
        unsafe_allow_html=True,
    )


def render_skill_analysis(report: MatchReport, extractor: SkillExtractor) -> None:
    result = report.result
    left, middle, right = st.columns(3, gap="large")

    with left:
        st.markdown(f"**Matched ({len(result.matched_skills)})**")
        st.markdown(chips(result.matched_skills, MATCHED, MATCHED_BG), unsafe_allow_html=True)
        if not result.matched_skills:
            st.caption("No skill from this job was found in the resume.")

    with middle:
        total_missing = len(result.missing_skills)
        st.markdown(f"**Missing ({total_missing})**")
        if not total_missing:
            st.markdown(
                f'<div class="rjm-sub" style="color:{MATCHED}">'
                "Every skill listed in the job description was found.</div>",
                unsafe_allow_html=True,
            )
        else:
            if result.required_gap.missing:
                st.markdown('<div class="rjm-sub">Required</div>', unsafe_allow_html=True)
                st.markdown(chips(result.required_gap.missing, MISSING, MISSING_BG),
                            unsafe_allow_html=True)
            if result.preferred_gap.missing:
                st.markdown('<div class="rjm-sub">Preferred</div>', unsafe_allow_html=True)
                st.markdown(chips(result.preferred_gap.missing, PREFERRED, PREFERRED_BG),
                            unsafe_allow_html=True)

    with right:
        st.markdown(f"**Additional skills ({len(report.additional_skills)})**")
        st.markdown('<div class="rjm-sub">Found in the resume, not asked for here</div>',
                    unsafe_allow_html=True)
        st.markdown(chips(report.additional_skills, MUTED, NEUTRAL_BG), unsafe_allow_html=True)

    with st.expander("How each skill was found in the resume"):
        rows = [
            {
                "Skill": skill,
                "Category": extractor.vocab.category_of(skill),
                "Found as": ", ".join(report.resume_skills.surfaces_for(skill)) or skill,
                "Evidence": report.resume_skills.evidence.get(skill, ""),
            }
            for skill in report.resume_skills.skills
        ]
        if rows:
            st.dataframe(pd.DataFrame(rows), hide_index=True, width="stretch")
        else:
            st.caption("No skills were extracted from the resume.")


def render_score_breakdown(report: MatchReport) -> None:
    st.markdown(
        '<div class="rjm-sub">Each component is scored from 0 to 1, multiplied by its '
        "effective weight, and summed. Components that could not be computed are skipped "
        "and their weight is shared across the rest, never counted as zero.</div>",
        unsafe_allow_html=True,
    )
    rows = [
        {
            "Component": component.label,
            "Score": f"{component.percent:.0f}%" if component.available else "not available",
            "Configured weight": f"{component.weight:.0%}",
            "Effective weight": f"{component.effective_weight:.0%}",
            "Points contributed": round(component.contribution, 1),
            "Detail": component.detail,
        }
        for component in report.result.components
    ]
    st.dataframe(pd.DataFrame(rows), hide_index=True, width="stretch")
    st.markdown(
        f'<div class="rjm-sub">Total: <strong>{report.overall_score:.1f} points</strong> '
        f"out of 100.</div>",
        unsafe_allow_html=True,
    )


def render_job_analysis(report: MatchReport) -> None:
    job = report.job
    left, right = st.columns(2, gap="large")
    with left:
        st.markdown(f"**Title** &nbsp; {esc(job.title)}", unsafe_allow_html=True)
        st.markdown(f"**Required ({len(job.required_skills)})**")
        st.markdown(chips(job.required_skills, ACCENT, "#EAEFF7"), unsafe_allow_html=True)
        st.markdown("**Preferred**")
        if job.preferred_skills:
            st.markdown(chips(job.preferred_skills, PREFERRED, PREFERRED_BG),
                        unsafe_allow_html=True)
        else:
            st.markdown('<div class="rjm-sub">Not explicitly specified</div>',
                        unsafe_allow_html=True)
        if job.other_skills:
            st.markdown("**Mentioned, but not stated as a requirement**")
            st.markdown(chips(job.other_skills, MUTED, NEUTRAL_BG), unsafe_allow_html=True)
    with right:
        st.markdown(f"**Experience required** &nbsp; {esc(job.experience.describe())}",
                    unsafe_allow_html=True)
        st.markdown(f"**Education required** &nbsp; {esc(job.education.describe())}",
                    unsafe_allow_html=True)
        st.markdown(
            f'<div class="rjm-sub">Sections detected: '
            f"{esc(', '.join(job.sections_detected) or 'none')}</div>",
            unsafe_allow_html=True,
        )
        if not job.explicit_requirements:
            st.warning(
                "No explicit Required or Preferred section was found, so every detected "
                "skill is treated as required."
            )
    if job.responsibilities:
        with st.expander("Responsibilities detected"):
            for item in job.responsibilities:
                st.markdown(f"- {item}")


# --------------------------------------------------------------------------- #
# Page
# --------------------------------------------------------------------------- #


def main() -> None:
    st.markdown(CSS, unsafe_allow_html=True)
    extractor = get_extractor()

    with st.sidebar:
        st.markdown("### Settings")
        backend_default = semantic_backend_available()
        backend = st.selectbox(
            "Semantic backend",
            ["auto", "lsa"],
            help=(
                "'auto' uses the sentence-transformer model when installed and falls "
                "back to Latent Semantic Analysis otherwise. 'lsa' forces the "
                "dependency-free fallback."
            ),
        )
        st.markdown(
            f'<div class="rjm-sub">Available: '
            f'{"sentence-transformers" if backend_default == "st" else "LSA fallback"}</div>',
            unsafe_allow_html=True,
        )

        st.markdown("### Scoring weights")
        st.markdown(
            '<div class="rjm-sub">Defaults are documented project assumptions, not '
            "tuned optimums. Move them and the score updates.</div>",
            unsafe_allow_html=True,
        )
        weights = (
            st.slider("Required skills", 0.0, 1.0, 0.40, 0.05),
            st.slider("Preferred skills", 0.0, 1.0, 0.15, 0.05),
            st.slider("Semantic similarity", 0.0, 1.0, 0.25, 0.05),
            st.slider("TF-IDF similarity", 0.0, 1.0, 0.10, 0.05),
            st.slider("Experience", 0.0, 1.0, 0.05, 0.05),
            st.slider("Education", 0.0, 1.0, 0.05, 0.05),
        )
        total = sum(weights)
        if abs(total - 1.0) > 0.001:
            st.info(f"Weights total {total:.2f}; they are normalised before scoring.")

        st.markdown("### Score bands")
        weak_max = st.slider("Weak up to", 0, 100, 39)
        moderate_max = st.slider("Moderate up to", weak_max, 100, max(69, weak_max))
        strong_max = st.slider("Strong up to", moderate_max, 100, max(84, moderate_max))

        st.divider()
        st.markdown(
            f'<div class="rjm-sub">Skill database: {len(extractor.vocab)} skills, '
            f"{len(extractor.vocab.alias_targets)} aliases</div>",
            unsafe_allow_html=True,
        )

    st.title("Resume-Job Matcher")
    st.markdown(
        '<p class="rjm-lede">Compare a resume against a job description and see which '
        "skills are missing. Built with traditional and semantic NLP: no language model "
        "is involved, so every figure below is computed from the extracted text and is "
        "reproducible.</p>",
        unsafe_allow_html=True,
    )

    left, right = st.columns(2, gap="large")
    with left:
        resume_text = document_input("Resume", "resume", SAMPLE_RESUMES_DIR, "01")
    with right:
        job_text = document_input("Job description", "job", SAMPLE_JOBS_DIR, "02")

    st.markdown('<h2><span class="rjm-step">03</span>Analyse</h2>', unsafe_allow_html=True)
    ready = bool(resume_text.strip() and job_text.strip())
    if not ready:
        st.markdown(
            '<div class="rjm-sub">Add a resume and a job description above. '
            'Pick "Use a sample" on both sides for a quick look.</div>',
            unsafe_allow_html=True,
        )
    analyse = st.button("Analyse match", type="primary", disabled=not ready)

    if not analyse:
        return

    thresholds = MatchThresholds(float(weak_max), float(moderate_max), float(strong_max))
    if backend == "auto" and backend_default == "st":
        warm_semantic_model(Settings().semantic_model_name)

    with st.spinner("Extracting skills, comparing text and scoring..."):
        try:
            report = run_analysis(
                resume_text, job_text, weights,
                (float(weak_max), float(moderate_max), float(strong_max)), backend,
            )
        except Exception:  # pragma: no cover - UI safety net
            st.error(
                "Something went wrong during the analysis. Try a different file, or "
                "paste the text directly."
            )
            st.stop()

    for warning in report.warnings:
        st.warning(warning)

    st.divider()
    render_verdict(report, thresholds)
    st.markdown("<div style='height:18px'></div>", unsafe_allow_html=True)
    render_dashboard(report)

    tabs = st.tabs(
        ["Skill analysis", "Score breakdown", "Job requirements",
         "Experience and education", "Raw output"]
    )

    with tabs[0]:
        render_skill_analysis(report, extractor)
    with tabs[1]:
        render_score_breakdown(report)
    with tabs[2]:
        render_job_analysis(report)
    with tabs[3]:
        left, right = st.columns(2, gap="large")
        with left:
            st.markdown("**Experience**")
            st.markdown(f"- Required: {report.job.experience.describe()}")
            st.markdown(f"- Found in resume: {report.resume_experience.describe()}")
            st.markdown(f"- Verdict: {report.experience_match.status}")
            if report.resume_experience.evidence:
                st.caption(f"Evidence: {report.resume_experience.evidence}")
        with right:
            st.markdown("**Education**")
            st.markdown(f"- Required: {report.job.education.describe()}")
            st.markdown(f"- Found in resume: {report.resume_education.describe()}")
            st.markdown(f"- Verdict: {report.education_match.status}")
            if report.resume_education.evidence:
                st.caption(f"Evidence: {report.resume_education.evidence}")
    with tabs[4]:
        st.json(report.to_dict())
        st.download_button(
            "Download this report as JSON",
            data=pd.Series(report.to_dict()).to_json(indent=2),
            file_name="match_report.json",
            mime="application/json",
        )

    st.markdown(
        '<div class="rjm-sub" style="margin-top:24px">Uploaded documents are processed in '
        "memory for this analysis only and are not stored by the application.</div>",
        unsafe_allow_html=True,
    )


if __name__ == "__main__":
    main()
